### ISSUE TITLE
Gene regulation page

### ISSUE THREAD

**Issue by omerfaruk84** [klevinb/check-app#6]
We need to have a page with the following items:

Title
Distribution Chart
Table

We need this 4 times.

We will remove 4 buttons on the side menu.

**Comment by klevinb** [comment]
![Screenshot 2023-02-16 at 03 33 55](https://user-images.githubusercontent.com/31502516/219253312-f045f895-be97-44e2-985b-065e44a2be33.png)

Issue was resolved.
